version: '3.3'
services: 
 mysql:
  image: mysql:5.6.47
  environment: 
   MYSQL_ROOT_PASSWORD: "123"
   TZ: America/Manaus
  ports:
   - '3307:3306'
  volumes:
   - mysql-db:/var/lib/mysql
volumes: 
 mysql-db:
networks:
 default:
  external:
   name: mysql-network
